name: 功能建议
description: 说明使用场景和期望结果
body:
  - type: textarea
    id: problem
    attributes:
      label: 想解决什么问题？
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: 期望行为与替代方案
    validations:
      required: true
